# TODO: fill in parameters and match with what is in AzureDevOps parameters

# parameters:
#   - name: 
#     displayName:
#     type:
#     default:

variables:
  server: viya4.apdemo.sas.com
  protocol: https
  azureSubscriptionEndpoint: apteam-viya4-aks-connection
  azureContainerRegistry: ssayjc.azurecr.io
  azureResourceGroup: ssayjc
  kubernetesCluster: apteam-viya4-aks
  useClusterAdmin: true

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TestPythonModel@1
  inputs:
    scriptSource: 'filepath'
    scriptPath: $(System.DefaultWorkingDirectory)/test_python_model.py

- task: DeployDecisionSCR@1
  inputs:
    scriptSource: 'filepath'
    scriptPath: $(System.DefaultWorkingDirectory)/deploy_decision_container.py

- task: Kubernetes@1
  displayName: kubectl re-deploy SCR decision container
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    useClusterAdmin: $(useClusterAdmin)
    command: rollout
    arguments: "restart deployment scr-decision-container"

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
